### ISSUE TITLE
will you release pretrained vocoder for test?

### ISSUE THREAD

**Issue by MaxMax2016** [zerlinwang/synthcoder#2]
this is a amazing work, TKS

**Comment by zerlinwang** [comment]
Sorry for the delay reply.
Thanks for your interest and star! This is the generator weights of HiFi-GAN trained with our synthetic corpus, *i.e.*, "Neural Vocoder (1M)" in the paper.
https://drive.google.com/drive/folders/1D9rYGhbrHtgr89Z8DzfopQfDLbSNKV6d?usp=sharing
